添加sfdrug
ybw0014/guizhan-builds pull request #336
Opened 2022-09-25 07:42 UTC by shixinzia

sfdrug

2022-09-25 20:50 UTC, ybw0014 requested changes

2022-09-25 20:50 UTC, ybw0014 commented on static/repos.json
> +}
多了一行

2022-09-25 20:50 UTC, ybw0014 commented on static/repos.json
> +        "SlimefunGuguProject/SFIllegalActivities:master": {
按照其他仓库名称的格式来

2022-09-25 20:50 UTC, ybw0014 commented on static/repos.json
> +            "customDir": "SlimefunGuguProject/SFIllegalActivities/master",
当仓库信息与自定义目录一致时不需要提供

2022-09-25 20:50 UTC, ybw0014 commented on static/repos.json
> +                "12": "Java 17+"
版本需求应覆盖全部版本

2022-09-30 21:26 UTC, ybw0014 requested changes

2022-09-30 21:26 UTC, ybw0014 commented on static/repos.json
> +                "1": "不需要"
注意花括号的配对

2022-09-30 22:57 UTC, ybw0014 approved these changes

2022-09-30 22:57 UTC, ybw0014 commented
晚点合并，我要试个新东西

2022-09-30 22:59 UTC, shixinzia commented
az


&nbsp;


心孜
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月1日(星期六) 上午6:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ybw0014/guizhan-builds] 添加sfdrug (PR #336)





 
晚点合并，我要试个新东西
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2022-09-30 23:17 UTC, ybw0014 commented
算了我先合并了

2022-09-30 23:17 UTC, merged